hyprwm/hyprland-plugins

hyprbars/Makefile, hyprbars/README.md, hyprbars/barDeco.cpp, hyprbars/main.cpp, hyprbars/meson.build
- use pangocairo to draw title: recommend way to render text.
- adds title padding and prevents title from overlapping with buttons: closes #7 
- If title is too long shorten it with an ellipsis
- add close and maximize colors to the config options
Don't code in C++ so I'm not sure how to best include `pangocairo.h` or how to update the meson.build. Not even sure how cario is already being included.
=> Hyprbars: Improve Title Rendering 

borders-plus-plus/default.nix, csgo-vulkan-fix/default.nix, hyprbars/default.nix
Use `pname` in place of `name` for plugin derivations. This makes `name` equal `${pname}-${version}`. This lets the hyprland flake locate plugin artifacts using `pname` (it does not use `name` because the derivation name often contains a version).
I have tested that all plugins are able to be loaded with this pr.
(@fufexan)
=> Use `pname` instead of `name` for plugin derivations

flake.nix
To make it easier for people using nix flakes to consume it.
=> nix: expose winwrap via flake

hyprbars/Makefile, hyprbars/meson.build
Fixes issue #63 
Both hyprland and wlroots is listed under the flags because there is a possibility of both a bundled wlroots and a wlroots package as a dependency. Worst case scenario I guess is that there might sometimes be an extra unneeded dependency.  
Based on my observations, it seems the bundled wlroots is more common in distro packages but some people might still use the wlroots package of their distro and use that if they compile from source. This could possibly break some existing plugin packages like the hyprland plugins package that is currently in the aur due to the dependency of wlroots. Feel free to remove hyprland or wlroots from the flags if you feel it is necessary.
=> Update pkgconfig flags of hyprbars to include irregular locations of headers on distros like openSUSE

borders-plus-plus/default.nix, csgo-vulkan-fix/default.nix, flake.lock, flake.nix, hyprbars/default.nix, hyprtrails/default.nix, hyprwinwrap/default.nix
This PR unifies the build mechanism in hyprland-plugins with the one in Nixpkgs.
This provides help for plugin developers wishing to write a derivation for their
plugin and checking this repo for examples.
The plugins build, but I haven't tested them. If you can, please do test them.
=> Nix: use mkHyprlandPlugin from nixpkgs

borders-plus-plus/CMakeLists.txt, borders-plus-plus/default.nix, csgo-vulkan-fix/CMakeLists.txt, csgo-vulkan-fix/default.nix, flake.lock, flake.nix, hyprbars/CMakeLists.txt, hyprbars/default.nix, hyprexpo/CMakeLists.txt, hyprexpo/default.nix, hyprtrails/CMakeLists.txt, hyprtrails/default.nix, hyprwinwrap/CMakeLists.txt, hyprwinwrap/default.nix
Complements hyprwm/Hyprland#5667
Switch Nix builds to use CMake instead of Meson. Meson might be deprecated in
the future.
Simplify overlay mechanism. Overlaying `hyprland.overlays.hyprland-packages` on
top of Nixpkgs works perfectly, whereas providing the flake package to the
`mkHyprlandPlugin` function does not. I might remove that feature in the future.
Feel free to test and report any issues.
=> treewide: add CMake files

hyprexpo/README.md, hyprexpo/main.cpp, hyprexpo/overview.cpp
I added a config value for gesture fingers and improved gesture detection by adding some checks so it doesn't get triggered when swiping horizontally or in the opposite direction of gesture_positive, this makes the gesture compatible with workspace swipe to use both gestures with the same number of fingers
=> expo: add option for gesture fingers

hyprexpo/main.cpp
I felt like a gesture to close the overview was missing, so I made it so doing the reverse of the opening gesture closes it.
I didn't quite know how to not duplicate the code, sorry about that.
=> expo: add swipe gesture to close overview

hyprexpo/main.cpp
the gesture to close the overview has a hardcoded distance value instead of using the config so i fixed it
=> expo: fix hardcoded distance value

borders-plus-plus/borderDeco.cpp, borders-plus-plus/borderDeco.hpp
fixed an issue where borders++ was not adhering to higher-priority sticky decorations (like hyprbars with border_precedence turned on) due to borders++ following the ABSOLUTE policy rather than STICKY. this addresses issue #215 
before (natural rounding off, 2 border++s, with hyprbars)
after
if u look closely, now there is no gaps between borders :+1: :smiley: 
there is still a gap between the shadows and borders, i think the only way to fix this is by making rounding be affected by sticky decos somehow, and then assigning it to the drop shadow. correct me if im wrong
edit: i meant borders++ oops
=> make borders++ sticky, fix scaling issues

borders-plus-plus/borderDeco.cpp, hyprbars/barDeco.cpp, hyprexpo/overview.cpp, hyprtrails/trail.cpp
Somehow the last commit only included the changes to hpp, not to cpp, this PR adapts the `draw` function signature as in that commit. Not sure if other changes are required. It builds at least, except hyprexpo:
```
overview.cpp: In member function 'void COverview::render()':
overview.cpp:403:91: error: 'Hyprutils::Memory::CSharedPointer<CTexture> CFramebuffer::m_cTex' is private within this context
403 |             g_pHyprOpenGL->renderTextureInternalWithDamage(images[x + y * SIDE_LENGTH].fb.m_cTex, &texbox, 1.0, &damage);
|                                                                                           ^~~~~~
/usr/include/hyprland/src/render/Framebuffer.hpp:24:18: note: declared private here
24 |     SP<CTexture> m_cTex;
|                  ^~~~~~
```
The second commit also …
=> Fix 60c5c63

hyprbars/main.cpp
This pull request includes a small fix to the error message in the `onNewButton` method of the `hyprbars/main.cpp` file. The change corrects the variable name referenced in the error message to accurately reflect the variable being validated. The error was missleading for me when configuring the plugin.
* Corrected the error message to reference `var0` instead of `var2` when `X` is not a valid number.
=> Hyprbars: Fix typo in error message

hyprexpo/overview.cpp
Re: https://github.com/hyprwm/Hyprland/commit/a5c14370c11287cbf520c8f427179c665ac9c891
I've opted to remove the optional parameters, since they match the defaults, so unless there is a specific reason for explicitly setting them this is easier
=> Fix `renderTextureInternalWithDamage` call for new parameter

borders-plus-plus/borderDeco.cpp, hyprtrails/trail.cpp
Fixes broken Hyprland function calls that were changed in hyprwm/Hyprland#8943.
Should fix #270.
=> all: add new `roundingPower` parameter to render function calls

hyprbars/README.md, hyprbars/barDeco.cpp, hyprbars/barDeco.hpp, hyprbars/globals.hpp, hyprbars/main.cpp, hyprexpo/overview.cpp
Task list:
- ~~Implement tablet/pen support~~, not looking very easy, will prob be done in another mr.
Note that as of 31/12/24 i no longer have access to a touch screen device in order to test touch functionality (it is being repaired).
~~(description below): There appears to be a bug where touching outside the main application (e.g. the border or the bar, i.e. A part of the window attached to the window but not the main application) causes touch down/click events to be sent to the application (?) which can open things like context menus.~~ again, fixed by the man himself (vaxry)
=> [hyprbars] Improve (touch + button) functionality

hyprbars/barDeco.cpp, hyprbars/barDeco.hpp
When clicking buttons on hyprbars, it doesn't disable drag, which causes problems if the click opens a new window/dialog as shown in the video.
first part of the video is the current behavior and second part is with this change.
https://github.com/user-attachments/assets/a977fb8e-a2f0-4ca0-9980-0d62389271e7
Edit: didn't see there was an issue, fixes #284
=> Hyprbars: disable drag when clicking button

hyprbars/barDeco.cpp
Some unicode characters didn't center properly, changing the width calculation to ink_rect fixes it, but it doesn't work for height too, so i kept logical_rect for height (same value from before, `pango_layout_get_size` [gets values from the logical_rect](https://docs.gtk.org/Pango/method.Layout.get_size.html)).
before:
after:
i think i saw some issue about it but can't find it now, maybe it was some other issue and someone just left a comment about it.
edit: add pic if using ink_rect for height:
=> Hyprbars: center button text

hyprwinwrap/main.cpp
https://github.com/hyprwm/Hyprland/commit/ff9e059de6dd30c813270ff5a74053339cc94765 changed how `sendWindowSize` should be called
=> hyprwinwrap: chase ff9e059

hyprbars/barDeco.cpp
Sets pango's base direction to netural for rendering title, fixes #285 
before:
#285 
after:
`bar_text_align = center`
`bar_text_align = left`
=> Hyprbars: fix title rendering for RTL text

hyprbars/barDeco.cpp, hyprbars/barDeco.hpp
This is how I fixed the 32-bit mismatch when [building for x86](https://gitlab.alpinelinux.org/rhizoome/aports/-/jobs/1793731#L461). Let me know if you want to fix it differently.
The problem arises because on one side Hyprlang::INT is used and on the other `long int`, which is `long long int` on 32bit.
=> hyprbars: fix type mismatch on 32-bit systems

hyprscrolling/Scrolling.cpp
right now you can move a window "outside the screen" with movewindowto
Instead the viewport should follow the window.
=> hyprscrolling: fix viewport should follow movewindowto

hyprexpo/README.md, hyprexpo/main.cpp, hyprexpo/overview.cpp, hyprexpo/overview.hpp
As the title says, i added a dispatcher argument "select" to select the currently hovered workspace.
This solves #361
=> expo: add dispatcher argument to select currently hovered workspace

hyprbars/barDeco.cpp
=> hyprbars: invalidate input when overlay and top shell layers are on top

hyprbars/README.md, hyprbars/barDeco.cpp, hyprbars/barDeco.hpp, hyprbars/main.cpp
Not sure about the proper option name. But this adds a way to customize the bg color of buttons on unfocused windows.
=> Add `inactive_button_color` option

flake.nix, hyprfocus/meson.build
added meson.build (copied from hyprscrolling, but alphabetized dependencies to match CMakeLists)
also added hyprfocus to flake.nix
=> hyprfocus: fix nix

hyprwinwrap/README.md, hyprwinwrap/main.cpp
Hi there!
The goal of this PR is to enhance `hyprwinwrap` by adding the ability to select a window by its title, in addition to the existing method of selecting by its class.
It closes #271 
Some applications (or specific instances of applications) may not have a unique class but can be identified by their window title. This change provides more flexibility for users to wrap the exact windows they want.
- Added a new configuration option: `plugin:hyprwinwrap:title`
- Updated `onNewWindow()` to check for a match on either class or title.
- Updated `onConfigReloaded()` to apply the necessary `windowrulev2` rules for titles.
=> feature(hyprwinwrap): adds option to select window by title

hyprscrolling/Scrolling.cpp
Set a corner to resize from.
Negate delta.y when resizing not-top window in the column. Seems to also fix using exact when resizing not-top window.
=> Hyprscrolling: Make resizeactive keyboard binds work for vertical window resizing

hyprscrolling/Scrolling.cpp
When using `no_focus_fallback`, a window in the last column focused but not (entirely) visible, using `layoutmsg focus right` does nothing. To bring the column in to view, you have to focus left, then `layoutmsg focus right` or use a 
This change makes `layoutmsg focus left,right` centerOrFit the column when the first or last column is active.
=> Hyprscrolling: centerOrFit with 'focus' when first or last column already focused.

hyprscrolling/Scrolling.cpp
SColumnData::down iterates over windowDatas till it matches the target window then swaps it with windowDatas[i + 1], becoming the next window in windowDatas so it matches every subsequent iteration till it's the last window in the column.
So break out after the swap().
Fixes https://github.com/hyprwm/hyprland-plugins/issues/452
=> hyprscrolling: SColumnData::down break after window swap

hyprscrolling/Scrolling.cpp, hyprscrolling/Scrolling.hpp
When you have two (or more) columns with different numbers of windows,  `layoutmsg focus l/r` always sends focus to the **top-most** window of the adjacent column, even if the current window is at the bottom. This feels unnatural (issue #473).
Introduce `findBestNeighbor()` that selects the window in the target column whose vertical span **overlaps the current window the top**.  If no overlap exists we fall back to the top-most window, preserving the old behaviour for edge cases.
```
col1       col2
-----------------------
|  term A  |  term B  |
|  term A  |  term B  |
|  term A  |----------|
|  term A  |  term D  |
|----------|  term D  |<-- if focus is here, movefocus l goes to term A
|  term C  |  term D  |
|  term C  |----------|
|  term C  |  term E  |
|  term C  |  term E  |<-- if …
```
=> Hyprscrolling: feat: focus left/right moves to the best vertical neighbour

hyprscrolling/README.md, hyprscrolling/Scrolling.cpp, hyprscrolling/Scrolling.hpp
This PR introduces two new layout messages for the `scrolling` layout: `swapcol` and `movecoltoworkspace`. These features significantly enhance workspace organization and address common user requests for more flexible column management.
As discussed in **Issue #431**, managing columns in the `scrolling` layout can be cumbersome. Users have pointed out the need for simpler ways to reorder columns and move them between workspaces without disrupting their internal structure. This PR directly addresses these needs by providing dedicated commands for these actions.
> As **@noctuid** noted:
> "Think this issue could be maybe more generic for column movement commands: directionally within a workspace and to move a column to another workspace"
This PR implements both of these suggestions.
1. …
=> Hyprscrolling: feat: Add column movement commands (`swapcol`, `movecoltoworkspace`)

borders-plus-plus/default.nix, csgo-vulkan-fix/default.nix, flake.lock, hyprbars/default.nix, hyprexpo/default.nix, hyprfocus/default.nix, hyprscrolling/default.nix, hyprtrails/default.nix, hyprwinwrap/default.nix, xtra-dispatchers/default.nix
Fix plugin derivations, caused by https://github.com/NixOS/nixpkgs/pull/443076
Closes #483
Was failing with:
```
hyprland-plugins on  build-fix:main [≡✶] via   
› nix flake check -L
warning: Git tree '/home/amadejk/Documents/hyprland-plugins' is dirty
error:
… while checking flake output 'packages'
at /nix/store/ngvxia8l1zvsq965vgxxna775fqrqggk-source/flake.nix:29:5:
28|   in {
29|     packages = eachSystem (system: {
|     ^
30|       inherit
… while checking the derivation 'packages.x86_64-linux.borders-plus-plus'
at /nix/store/ngvxia8l1zvsq965vgxxna775fqrqggk-source/flake.nix:32:9:
31|         (pkgsFor.${system}.hyprlandPlugins)
32|         borders-plus-plus
|         ^
33|         csgo-vulkan-fix
(stack trace truncated; use '--show-trace' to show the full trace)
error: The `env` …
```
=> chore: chase nixpkgs

borders-plus-plus/default.nix, csgo-vulkan-fix/default.nix, flake.lock, hyprbars/default.nix, hyprexpo/default.nix, hyprfocus/default.nix, hyprscrolling/Scrolling.cpp, hyprscrolling/Scrolling.hpp, hyprscrolling/default.nix, hyprtrails/default.nix, hyprwinwrap/default.nix, xtra-dispatchers/default.nix
This PR introduces a more intelligent focus behavior for the scrolling layout, resolving issues where focus would jump unpredictably when moving between columns with different window arrangements.
**Changes:**
1.  **Last Focused Window Tracking:** Each column now remembers the last window that had focus within it via a `WP<SScrollingWindowData> lastFocusedWindow`.
2.  **New `findBestNeighbor` Logic:** The algorithm for finding the next window to focus when moving left or right has been rewritten. It now:
*   Prioritizes the `lastFocusedWindow` in the target column, but only if it vertically overlaps with the current window.
*   Falls back to the top-most vertically overlapping window if the historical choice is not applicable.
*   Falls back again to the first window in the column if …
=> Hyprscrolling: feat: improve focus stability with last-focused memory
